### PR TITLE
upload figures in the matrial folder

### PR DESCRIPTION
**Pull request by Bayquiri**
and add a row in the material-metadata.csv file

### CODE REVIEW

**Comment by jcolomb** [comment]
file name should be complete, including the ".pdf" in the .csv file.

**Comment by jcolomb** [comment]
please modify the .csv file and commit + push, it will then appear here :)

**Comment by jcolomb** [comment]
sorry, there is still a problem, second column should be "1" otherwise it does not show up in the website.
BTW, you can check in the "show all checks" + details whether the website show the elements.

**Comment by Bayquiri** [comment]
Thank you very much.

**Comment by jcolomb** [comment]
still not working, but I will solve it after merge

**Comment by jcolomb** [comment]
thank you, it is now live !

**Pull request merged**
